/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinInviteCodeRouteImport } from './routes/join.$inviteCode'
import { Route as AppReportRouteImport } from './routes/app.report'
import { Route as AppReceiptSplitRouteImport } from './routes/app.receipt-split'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBalancesRouteImport } from './routes/app.balances'
import { Route as AppAddExpenseRouteImport } from './routes/app.add-expense'
import { Route as AppTripIdRouteImport } from './routes/app.trip.$id'
import { Route as AppTripIdSettingsRouteImport } from './routes/app.trip.$id.settings'
import { Route as AppTripIdInviteRouteImport } from './routes/app.trip.$id.invite'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptSplitRoute = AppReceiptSplitRouteImport.update({
  id: '/receipt-split',
  path: '/receipt-split',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBalancesRoute = AppBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => AppRoute,
} as any)
const AppAddExpenseRoute = AppAddExpenseRouteImport.update({
  id: '/add-expense',
  path: '/add-expense',
  getParentRoute: () => AppRoute,
} as any)
const AppTripIdRoute = AppTripIdRouteImport.update({
  id: '/trip/$id',
  path: '/trip/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTripIdSettingsRoute = AppTripIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppTripIdRoute,
} as any)
const AppTripIdInviteRoute = AppTripIdInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppTripIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/add-expense': typeof AppAddExpenseRoute
  '/app/balances': typeof AppBalancesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/receipt-split': typeof AppReceiptSplitRoute
  '/app/report': typeof AppReportRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/app/trip/$id': typeof AppTripIdRouteWithChildren
  '/app/trip/$id/invite': typeof AppTripIdInviteRoute
  '/app/trip/$id/settings': typeof AppTripIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/add-expense': typeof AppAddExpenseRoute
  '/app/balances': typeof AppBalancesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/receipt-split': typeof AppReceiptSplitRoute
  '/app/report': typeof AppReportRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/app/trip/$id': typeof AppTripIdRouteWithChildren
  '/app/trip/$id/invite': typeof AppTripIdInviteRoute
  '/app/trip/$id/settings': typeof AppTripIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/add-expense': typeof AppAddExpenseRoute
  '/app/balances': typeof AppBalancesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/receipt-split': typeof AppReceiptSplitRoute
  '/app/report': typeof AppReportRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/app/trip/$id': typeof AppTripIdRouteWithChildren
  '/app/trip/$id/invite': typeof AppTripIdInviteRoute
  '/app/trip/$id/settings': typeof AppTripIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/add-expense'
    | '/app/balances'
    | '/app/dashboard'
    | '/app/receipt-split'
    | '/app/report'
    | '/join/$inviteCode'
    | '/app/trip/$id'
    | '/app/trip/$id/invite'
    | '/app/trip/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/add-expense'
    | '/app/balances'
    | '/app/dashboard'
    | '/app/receipt-split'
    | '/app/report'
    | '/join/$inviteCode'
    | '/app/trip/$id'
    | '/app/trip/$id/invite'
    | '/app/trip/$id/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/add-expense'
    | '/app/balances'
    | '/app/dashboard'
    | '/app/receipt-split'
    | '/app/report'
    | '/join/$inviteCode'
    | '/app/trip/$id'
    | '/app/trip/$id/invite'
    | '/app/trip/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/report': {
      id: '/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipt-split': {
      id: '/app/receipt-split'
      path: '/receipt-split'
      fullPath: '/app/receipt-split'
      preLoaderRoute: typeof AppReceiptSplitRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/balances': {
      id: '/app/balances'
      path: '/balances'
      fullPath: '/app/balances'
      preLoaderRoute: typeof AppBalancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/add-expense': {
      id: '/app/add-expense'
      path: '/add-expense'
      fullPath: '/app/add-expense'
      preLoaderRoute: typeof AppAddExpenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trip/$id': {
      id: '/app/trip/$id'
      path: '/trip/$id'
      fullPath: '/app/trip/$id'
      preLoaderRoute: typeof AppTripIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trip/$id/settings': {
      id: '/app/trip/$id/settings'
      path: '/settings'
      fullPath: '/app/trip/$id/settings'
      preLoaderRoute: typeof AppTripIdSettingsRouteImport
      parentRoute: typeof AppTripIdRoute
    }
    '/app/trip/$id/invite': {
      id: '/app/trip/$id/invite'
      path: '/invite'
      fullPath: '/app/trip/$id/invite'
      preLoaderRoute: typeof AppTripIdInviteRouteImport
      parentRoute: typeof AppTripIdRoute
    }
  }
}

interface AppTripIdRouteChildren {
  AppTripIdInviteRoute: typeof AppTripIdInviteRoute
  AppTripIdSettingsRoute: typeof AppTripIdSettingsRoute
}

const AppTripIdRouteChildren: AppTripIdRouteChildren = {
  AppTripIdInviteRoute: AppTripIdInviteRoute,
  AppTripIdSettingsRoute: AppTripIdSettingsRoute,
}

const AppTripIdRouteWithChildren = AppTripIdRoute._addFileChildren(
  AppTripIdRouteChildren,
)

interface AppRouteChildren {
  AppAddExpenseRoute: typeof AppAddExpenseRoute
  AppBalancesRoute: typeof AppBalancesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppReceiptSplitRoute: typeof AppReceiptSplitRoute
  AppReportRoute: typeof AppReportRoute
  AppTripIdRoute: typeof AppTripIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAddExpenseRoute: AppAddExpenseRoute,
  AppBalancesRoute: AppBalancesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppReceiptSplitRoute: AppReceiptSplitRoute,
  AppReportRoute: AppReportRoute,
  AppTripIdRoute: AppTripIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
